apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo
spec:
  containers:
  - name: default-mem-demo-ctr
    image: iliasjdemoscr.azurecr.io/demoapp:latest
    resources:
        requests:
          memory: "128Mi"
