kind: Deployment
apiVersion: extensions/v1beta1
metadata:
 name: demoapp
 labels:
   app: demoapp
spec:
 replicas: 1
 selector:
   matchLabels:
    app: demoapp
 template:
   spec:
     containers:
       - name: cachecontainer
         image: redis:5.0.3-alpine
         resources:
           limits:
             memory: 600Mi
             cpu: 1
           requests:
             memory: 300Mi
             cpu: 500m
       - name: demoappcontainer
         image: iliasjeyscr.azurecr.io/eydemoapp:latest
         resources:
           limits:
             memory: 200Mi
             cpu: 300m
           requests:
             memory: 100Mi
             cpu: 100m
