apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-demo
spec:
  containers:
  - name: constraints-cpu-demo-container
    image: iliasjeyscr.azurecr.io/eydemoapp:latest
    resources:
      limits:
        cpu: "800m"
      requests:
        cpu: "500m"
