apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-demo-2
spec:
  containers:
  - name: constraints-cpu-demo-2-ctr
    image: iliasjeyscr.azurecr.io/eydemoapp:latest
    resources:
      limits:
        cpu: "1.5"
      requests:
        cpu: "500m"
