apiVersion: apps/v1
kind: Deployment
metadata:
  name: eydemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eydemoapp
  template:
    metadata:
      labels:
        app: eydemoapp
    spec:
      containers:
      - name: eydemoapp
        image: iliasjeyscr.azurecr.io/eydemoapp:latest
        ports:
        - containerPort: 80

        
