apiVersion: v1
kind: Pod
metadata:
  name: test-aadpod
  labels:
    aadpodidbinding: test-keyvault-access
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/azure-cli
    command:
      - sleep
      - "3600"