apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: "someidentity"               # The name of your Azure identity
spec:
    type: 0                                 # Set type: 0 for managed service identity
    resourceID: /subscriptions/7fbd5782-682d-442e-a6d3-970227de186d/resourcegroups/iliasj-aks-ey-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/someidentity
    clientID: "d9b7a989-01a2-4cdc-a509-fed3ea5bba26"     # The clientId of the Azure AD identity that you created earlier
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: "someidentity"      # The name of your Azure identity
    selector: azure-pod-identity-binding-selector